[package]
name = "CorundumAllocator"
version = "0.1.0"
edition = "2021"
authors = ["victoryang00 <victoryang00@ucsc.edu>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"corundum" = "0.4.1"